const { SITE_URL } = require("./metadata");

const DISALLOW_PATHS = [
  "/api/",
  "/admin/",
  "/_next/data/",
  "/_vercel/",
  "/private/",
  "/offline",
  "/monitoring",
  "/tmp/",
];

const ALLOWED_SEARCH_BOTS = [
  "*",
  "Googlebot",
  "Bingbot",
  "Applebot",
  "OAI-SearchBot",
  "Claude-SearchBot",
  "PerplexityBot",
];

const BLOCKED_TRAINING_BOTS = [
  "GPTBot",
  "ClaudeBot",
  "Google-Extended",
  "Applebot-Extended",
  "CCBot",
];

function renderAllowedRule(userAgent) {
  const lines = [`User-agent: ${userAgent}`, "Allow: /"];
  for (const disallowPath of DISALLOW_PATHS) {
    lines.push(`Disallow: ${disallowPath}`);
  }
  return lines.join("\n");
}

function renderBlockedRule(userAgent) {
  return [`User-agent: ${userAgent}`, "Disallow: /"].join("\n");
}

function renderRobotsTxt() {
  const allowedRules = ALLOWED_SEARCH_BOTS.map(renderAllowedRule).join("\n\n");
  const blockedRules = BLOCKED_TRAINING_BOTS.map(renderBlockedRule).join("\n\n");

  return `# Prosepal robots.txt
# Generated by scripts/generate-robots.js

# Allowed search and assistant-indexing crawlers
${allowedRules}

# Block model-training crawlers
${blockedRules}

Sitemap: ${SITE_URL}/sitemap.xml
`;
}

module.exports = {
  DISALLOW_PATHS,
  ALLOWED_SEARCH_BOTS,
  BLOCKED_TRAINING_BOTS,
  renderRobotsTxt,
};
