#!/usr/bin/env node

const fs = require("node:fs");
const path = require("node:path");
const { SITE_URL } = require("./lib/metadata");

const ROOT_DIR = path.join(__dirname, "..");
const OUTPUT_FILE = path.join(ROOT_DIR, "public", "robots.txt");
const DISALLOW_PATHS = [
  "/api/",
  "/admin/",
  "/_next/data/",
  "/_vercel/",
  "/private/",
  "/offline",
  "/monitoring",
  "/tmp/",
];
const ALLOWED_SEARCH_BOTS = [
  "*",
  "Googlebot",
  "Bingbot",
  "Applebot",
  "OAI-SearchBot",
  "Claude-SearchBot",
  "PerplexityBot",
];
const BLOCKED_TRAINING_BOTS = [
  "GPTBot",
  "ClaudeBot",
  "Google-Extended",
  "Applebot-Extended",
  "CCBot",
];

function renderAllowedRule(userAgent) {
  const lines = [`User-agent: ${userAgent}`, "Allow: /"];
  for (const disallowPath of DISALLOW_PATHS) {
    lines.push(`Disallow: ${disallowPath}`);
  }
  return lines.join("\n");
}

function renderBlockedRule(userAgent) {
  return [`User-agent: ${userAgent}`, "Disallow: /"].join("\n");
}

function main() {
  const allowedRules = ALLOWED_SEARCH_BOTS.map(renderAllowedRule).join("\n\n");
  const blockedRules = BLOCKED_TRAINING_BOTS.map(renderBlockedRule).join("\n\n");
  const content = `# Prosepal robots.txt
# Generated by scripts/generate-robots.js

# Allowed search and assistant-indexing crawlers
${allowedRules}

# Block model-training crawlers
${blockedRules}

Sitemap: ${SITE_URL}/sitemap.xml
`;

  fs.writeFileSync(OUTPUT_FILE, content, "utf8");
  console.log(`Generated robots.txt -> ${OUTPUT_FILE}`);
}

main();
